// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2

package handler

import (
	"net/http"

	api "zero/zerogen-tmp/internal/handler/api"
	attachment "zero/zerogen-tmp/internal/handler/attachment"
	authority "zero/zerogen-tmp/internal/handler/authority"
	authorityBtn "zero/zerogen-tmp/internal/handler/authorityBtn"
	autoCode "zero/zerogen-tmp/internal/handler/autoCode"
	autoCodeHistory "zero/zerogen-tmp/internal/handler/autoCodeHistory"
	base "zero/zerogen-tmp/internal/handler/base"
	casbin "zero/zerogen-tmp/internal/handler/casbin"
	email "zero/zerogen-tmp/internal/handler/email"
	example "zero/zerogen-tmp/internal/handler/example"
	file "zero/zerogen-tmp/internal/handler/file"
	info "zero/zerogen-tmp/internal/handler/info"
	jwt "zero/zerogen-tmp/internal/handler/jwt"
	menu "zero/zerogen-tmp/internal/handler/menu"
	skills "zero/zerogen-tmp/internal/handler/skills"
	sysApiToken "zero/zerogen-tmp/internal/handler/sysApiToken"
	sysDictionary "zero/zerogen-tmp/internal/handler/sysDictionary"
	sysDictionaryDetail "zero/zerogen-tmp/internal/handler/sysDictionaryDetail"
	sysError "zero/zerogen-tmp/internal/handler/sysError"
	sysExportTemplate "zero/zerogen-tmp/internal/handler/sysExportTemplate"
	sysLoginLog "zero/zerogen-tmp/internal/handler/sysLoginLog"
	sysOperationRecord "zero/zerogen-tmp/internal/handler/sysOperationRecord"
	sysParams "zero/zerogen-tmp/internal/handler/sysParams"
	sysVersion "zero/zerogen-tmp/internal/handler/sysVersion"
	system "zero/zerogen-tmp/internal/handler/system"
	user "zero/zerogen-tmp/internal/handler/user"
	"zero/zerogen-tmp/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.CasbinHandler},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/createApi",
					Handler: api.CreateApiHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/deleteApi",
					Handler: api.DeleteApiHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/deleteApisByIds",
					Handler: api.DeleteApisByIdsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/enterSyncApi",
					Handler: api.EnterSyncApiHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/freshCasbin",
					Handler: api.FreshCasbinHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/getAllApis",
					Handler: api.GetAllApisHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/getApiById",
					Handler: api.GetApiByIdHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/getApiGroups",
					Handler: api.GetApiGroupsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/getApiList",
					Handler: api.GetApiListHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/getApiRoles",
					Handler: api.GetApiRolesHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/ignoreApi",
					Handler: api.IgnoreApiHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/setApiRoles",
					Handler: api.SetApiRolesHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/syncApi",
					Handler: api.SyncApiHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/updateApi",
					Handler: api.UpdateApiHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.CasbinHandler},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/addCategory",
					Handler: attachment.AddCategoryHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/deleteCategory",
					Handler: attachment.DeleteCategoryHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/getCategoryList",
					Handler: attachment.GetCategoryListHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/attachmentCategory"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.CasbinHandler},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/copyAuthority",
					Handler: authority.CopyAuthorityHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/createAuthority",
					Handler: authority.CreateAuthorityHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/deleteAuthority",
					Handler: authority.DeleteAuthorityHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/getAuthorityList",
					Handler: authority.GetAuthorityListHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/getUsersByAuthority",
					Handler: authority.GetUsersByAuthorityHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/setDataAuthority",
					Handler: authority.SetDataAuthorityHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/setRoleUsers",
					Handler: authority.SetRoleUsersHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/updateAuthority",
					Handler: authority.UpdateAuthorityHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/authority"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.CasbinHandler},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/canRemoveAuthorityBtn",
					Handler: authorityBtn.CanRemoveAuthorityBtnHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/getAuthorityBtn",
					Handler: authorityBtn.GetAuthorityBtnHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/setAuthorityBtn",
					Handler: authorityBtn.SetAuthorityBtnHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/authorityBtn"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.CasbinHandler},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/addFunc",
					Handler: autoCode.AddFuncHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/createPackage",
					Handler: autoCode.CreatePackageHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/createTemp",
					Handler: autoCode.CreateTempHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/delPackage",
					Handler: autoCode.DelPackageHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/deleteAIWorkflowSession",
					Handler: autoCode.DeleteAIWorkflowSessionHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/dumpAIWorkflowMarkdown",
					Handler: autoCode.DumpAIWorkflowMarkdownHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/getAIWorkflowSessionDetail",
					Handler: autoCode.GetAIWorkflowSessionDetailHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/getAIWorkflowSessionList",
					Handler: autoCode.GetAIWorkflowSessionListHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/getColumn",
					Handler: autoCode.GetColumnHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/getDB",
					Handler: autoCode.GetDBHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/getPackage",
					Handler: autoCode.GetPackageHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/getPluginList",
					Handler: autoCode.GetPluginListHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/getTables",
					Handler: autoCode.GetTablesHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/getTemplates",
					Handler: autoCode.GetTemplatesHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/initAPI",
					Handler: autoCode.InitAPIHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/initDictionary",
					Handler: autoCode.InitDictionaryHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/initMenu",
					Handler: autoCode.InitMenuHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/installPlugin",
					Handler: autoCode.InstallPluginHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/llmAuto",
					Handler: autoCode.LLMAutoHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/llmAutoSSE",
					Handler: autoCode.LLMAutoSSEHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/mcp",
					Handler: autoCode.McpHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/mcpList",
					Handler: autoCode.McpListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/mcpRoutes",
					Handler: autoCode.McpRoutesHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/mcpStart",
					Handler: autoCode.McpStartHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/mcpStatus",
					Handler: autoCode.McpStatusHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/mcpStop",
					Handler: autoCode.McpStopHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/mcpTest",
					Handler: autoCode.McpTestHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/preview",
					Handler: autoCode.PreviewHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/pubPlug",
					Handler: autoCode.PubPlugHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/removePlugin",
					Handler: autoCode.RemovePluginHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/saveAIWorkflowSession",
					Handler: autoCode.SaveAIWorkflowSessionHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/autoCode"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.CasbinHandler},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/delSysHistory",
					Handler: autoCodeHistory.DelSysHistoryHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/getMeta",
					Handler: autoCodeHistory.GetMetaHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/getSysHistory",
					Handler: autoCodeHistory.GetSysHistoryHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/rollback",
					Handler: autoCodeHistory.RollbackHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/autoCode"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/base/captcha",
				Handler: base.CaptchaHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/base/login",
				Handler: base.LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/health",
				Handler: base.HealthHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/init/checkdb",
				Handler: base.CheckDBHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/init/initdb",
				Handler: base.InitDBHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.CasbinHandler},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/getPolicyPathByAuthorityId",
					Handler: casbin.GetPolicyPathByAuthorityIdHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/updateCasbin",
					Handler: casbin.UpdateCasbinHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/casbin"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.JwtHandler, serverCtx.CasbinHandler},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/emailTest",
					Handler: email.EmailTestHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/sendEmail",
					Handler: email.SendEmailHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/email"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.CasbinHandler},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/customer",
					Handler: example.CreateCustomerHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/customer",
					Handler: example.UpdateCustomerHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/customer",
					Handler: example.DeleteCustomerHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/customer",
					Handler: example.GetCustomerHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/customerList",
					Handler: example.GetCustomerListHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/customer"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.CasbinHandler},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/breakpointContinue",
					Handler: file.BreakpointContinueHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/breakpointContinueFinish",
					Handler: file.BreakpointContinueFinishHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/deleteFile",
					Handler: file.DeleteFileHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/editFileName",
					Handler: file.EditFileNameHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/findFile",
					Handler: file.FindFileHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/getFileList",
					Handler: file.GetFileListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/importURL",
					Handler: file.ImportFileUrlHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/removeChunk",
					Handler: file.RemoveChunkHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/upload",
					Handler: file.UploadFileHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/fileUploadAndDownload"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.JwtHandler, serverCtx.CasbinHandler},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/createInfo",
					Handler: info.CreateInfoHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/deleteInfo",
					Handler: info.DeleteInfoHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/deleteInfoByIds",
					Handler: info.DeleteInfoByIdsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/findInfo",
					Handler: info.FindInfoHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/getInfoDataSource",
					Handler: info.GetInfoDataSourceHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/getInfoList",
					Handler: info.GetInfoListHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/getInfoPublic",
					Handler: info.GetInfoPublicHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/updateInfo",
					Handler: info.UpdateInfoHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/info"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.CasbinHandler},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/jsonInBlacklist",
					Handler: jwt.JsonInBlacklistHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/jwt"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.CasbinHandler},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/addBaseMenu",
					Handler: menu.AddBaseMenuHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/addMenuAuthority",
					Handler: menu.AddMenuAuthorityHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/deleteBaseMenu",
					Handler: menu.DeleteBaseMenuHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/getBaseMenuById",
					Handler: menu.GetBaseMenuByIdHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/getBaseMenuTree",
					Handler: menu.GetBaseMenuTreeHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/getMenu",
					Handler: menu.GetMenuHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/getMenuAuthority",
					Handler: menu.GetMenuAuthorityHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/getMenuList",
					Handler: menu.GetMenuListHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/getMenuRoles",
					Handler: menu.GetMenuRolesHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/setMenuRoles",
					Handler: menu.SetMenuRolesHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/updateBaseMenu",
					Handler: menu.UpdateBaseMenuHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/menu"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.CasbinHandler},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/createReference",
					Handler: skills.CreateReferenceHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/createResource",
					Handler: skills.CreateResourceHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/createScript",
					Handler: skills.CreateScriptHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/createTemplate",
					Handler: skills.CreateTemplateHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/deleteSkill",
					Handler: skills.DeleteSkillHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/downloadOnlineSkill",
					Handler: skills.DownloadOnlineSkillHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/getGlobalConstraint",
					Handler: skills.GetGlobalConstraintHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/getReference",
					Handler: skills.GetReferenceHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/getResource",
					Handler: skills.GetResourceHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/getScript",
					Handler: skills.GetScriptHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/getSkillDetail",
					Handler: skills.GetSkillDetailHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/getSkillList",
					Handler: skills.GetSkillListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/getTemplate",
					Handler: skills.GetTemplateHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/getTools",
					Handler: skills.GetToolsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/packageSkill",
					Handler: skills.PackageSkillHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/saveGlobalConstraint",
					Handler: skills.SaveGlobalConstraintHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/saveReference",
					Handler: skills.SaveReferenceHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/saveResource",
					Handler: skills.SaveResourceHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/saveScript",
					Handler: skills.SaveScriptHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/saveSkill",
					Handler: skills.SaveSkillHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/saveTemplate",
					Handler: skills.SaveTemplateHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/skills"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.CasbinHandler},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/createApiToken",
					Handler: sysApiToken.CreateApiTokenHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/deleteApiToken",
					Handler: sysApiToken.DeleteApiTokenHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/getApiTokenList",
					Handler: sysApiToken.GetApiTokenListHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/sysApiToken"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.CasbinHandler},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/createSysDictionary",
					Handler: sysDictionary.CreateSysDictionaryHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/deleteSysDictionary",
					Handler: sysDictionary.DeleteSysDictionaryHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/exportSysDictionary",
					Handler: sysDictionary.ExportSysDictionaryHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/findSysDictionary",
					Handler: sysDictionary.FindSysDictionaryHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/getSysDictionaryList",
					Handler: sysDictionary.GetSysDictionaryListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/importSysDictionary",
					Handler: sysDictionary.ImportSysDictionaryHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/updateSysDictionary",
					Handler: sysDictionary.UpdateSysDictionaryHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/sysDictionary"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.CasbinHandler},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/createSysDictionaryDetail",
					Handler: sysDictionaryDetail.CreateSysDictionaryDetailHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/deleteSysDictionaryDetail",
					Handler: sysDictionaryDetail.DeleteSysDictionaryDetailHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/findSysDictionaryDetail",
					Handler: sysDictionaryDetail.FindSysDictionaryDetailHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/getDictionaryDetailsByParent",
					Handler: sysDictionaryDetail.GetDictionaryDetailsByParentHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/getDictionaryPath",
					Handler: sysDictionaryDetail.GetDictionaryPathHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/getDictionaryTreeList",
					Handler: sysDictionaryDetail.GetDictionaryTreeListHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/getDictionaryTreeListByType",
					Handler: sysDictionaryDetail.GetDictionaryTreeListByTypeHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/getSysDictionaryDetailList",
					Handler: sysDictionaryDetail.GetSysDictionaryDetailListHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/updateSysDictionaryDetail",
					Handler: sysDictionaryDetail.UpdateSysDictionaryDetailHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/sysDictionaryDetail"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.CasbinHandler},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/createSysError",
					Handler: sysError.CreateSysErrorHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/deleteSysError",
					Handler: sysError.DeleteSysErrorHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/deleteSysErrorByIds",
					Handler: sysError.DeleteSysErrorByIdsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/findSysError",
					Handler: sysError.FindSysErrorHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/getSysErrorList",
					Handler: sysError.GetSysErrorListHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/getSysErrorSolution",
					Handler: sysError.GetSysErrorSolutionHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/updateSysError",
					Handler: sysError.UpdateSysErrorHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/sysError"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.CasbinHandler},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/createSysExportTemplate",
					Handler: sysExportTemplate.CreateSysExportTemplateHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/deleteSysExportTemplate",
					Handler: sysExportTemplate.DeleteSysExportTemplateHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/deleteSysExportTemplateByIds",
					Handler: sysExportTemplate.DeleteSysExportTemplateByIdsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/exportExcel",
					Handler: sysExportTemplate.ExportExcelHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/exportExcelByToken",
					Handler: sysExportTemplate.ExportExcelByTokenHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/exportTemplate",
					Handler: sysExportTemplate.ExportTemplateHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/exportTemplateByToken",
					Handler: sysExportTemplate.ExportTemplateByTokenHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/findSysExportTemplate",
					Handler: sysExportTemplate.FindSysExportTemplateHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/getSysExportTemplateList",
					Handler: sysExportTemplate.GetSysExportTemplateListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/importExcel",
					Handler: sysExportTemplate.ImportExcelHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/previewSQL",
					Handler: sysExportTemplate.PreviewSQLHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/updateSysExportTemplate",
					Handler: sysExportTemplate.UpdateSysExportTemplateHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/sysExportTemplate"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.CasbinHandler},
			[]rest.Route{
				{
					Method:  http.MethodDelete,
					Path:    "/deleteLoginLog",
					Handler: sysLoginLog.DeleteLoginLogHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/deleteLoginLogByIds",
					Handler: sysLoginLog.DeleteLoginLogByIdsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/findLoginLog",
					Handler: sysLoginLog.FindLoginLogHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/getLoginLogList",
					Handler: sysLoginLog.GetLoginLogListHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/sysLoginLog"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.CasbinHandler},
			[]rest.Route{
				{
					Method:  http.MethodDelete,
					Path:    "/deleteSysOperationRecord",
					Handler: sysOperationRecord.DeleteSysOperationRecordHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/deleteSysOperationRecordByIds",
					Handler: sysOperationRecord.DeleteSysOperationRecordByIdsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/findSysOperationRecord",
					Handler: sysOperationRecord.FindSysOperationRecordHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/getSysOperationRecordList",
					Handler: sysOperationRecord.GetSysOperationRecordListHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/sysOperationRecord"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.CasbinHandler},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/createSysParams",
					Handler: sysParams.CreateSysParamsHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/deleteSysParams",
					Handler: sysParams.DeleteSysParamsHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/deleteSysParamsByIds",
					Handler: sysParams.DeleteSysParamsByIdsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/findSysParams",
					Handler: sysParams.FindSysParamsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/getSysParam",
					Handler: sysParams.GetSysParamHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/getSysParamsList",
					Handler: sysParams.GetSysParamsListHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/updateSysParams",
					Handler: sysParams.UpdateSysParamsHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/sysParams"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.CasbinHandler},
			[]rest.Route{
				{
					Method:  http.MethodDelete,
					Path:    "/deleteSysVersion",
					Handler: sysVersion.DeleteSysVersionHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/deleteSysVersionByIds",
					Handler: sysVersion.DeleteSysVersionByIdsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/downloadVersionJson",
					Handler: sysVersion.DownloadVersionJsonHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/exportVersion",
					Handler: sysVersion.ExportVersionHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/findSysVersion",
					Handler: sysVersion.FindSysVersionHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/getSysVersionList",
					Handler: sysVersion.GetSysVersionListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/importVersion",
					Handler: sysVersion.ImportVersionHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/sysVersion"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.CasbinHandler},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/getServerInfo",
					Handler: system.GetServerInfoHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/getSystemConfig",
					Handler: system.GetSystemConfigHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/reloadSystem",
					Handler: system.ReloadSystemHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/setSystemConfig",
					Handler: system.SetSystemConfigHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/system"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.CasbinHandler},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/admin_register",
					Handler: user.RegisterHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/changePassword",
					Handler: user.ChangePasswordHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/deleteUser",
					Handler: user.DeleteUserHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/getUserInfo",
					Handler: user.GetUserInfoHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/getUserList",
					Handler: user.GetUserListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/resetPassword",
					Handler: user.ResetPasswordHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/setSelfInfo",
					Handler: user.SetSelfInfoHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/setSelfSetting",
					Handler: user.SetSelfSettingHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/setUserAuthorities",
					Handler: user.SetUserAuthoritiesHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/setUserAuthority",
					Handler: user.SetUserAuthorityHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/setUserInfo",
					Handler: user.SetUserInfoHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/user"),
	)
}
