// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2

package types

type AIWorkflowSession struct {
	ID        uint   `json:"ID"`
	CreatedAt string `json:"CreatedAt"`
	UpdatedAt string `json:"UpdatedAt"`
	Name      string `json:"name"`
	Content   string `json:"content"`
	UserId    uint   `json:"userId"`
}

type AIWorkflowSessionDetailRes struct {
	Session AIWorkflowSession `json:"session"`
}

type AddFuncReq struct {
	Name    string `json:"name"`
	Content string `json:"content"`
}

type AddMenuAuthorityReq struct {
	MenuId      uint `json:"menuId"`
	AuthorityId uint `json:"authorityId"`
}

type AddMenuReq struct {
	ID          uint         `json:"id,optional"`
	CreatedAt   int64        `json:"createdAt,optional"`
	UpdatedAt   int64        `json:"updatedAt,optional"`
	DeletedAt   int64        `json:"deletedAt,optional"`
	MenuLevel   uint         `json:"menuLevel"`
	ParentId    uint         `json:"parentId"`
	Path        string       `json:"path"`
	Name        string       `json:"name"`
	Component   string       `json:"component"`
	Redirect    string       `json:"redirect,optional"`
	Title       string       `json:"title"`
	Icon        string       `json:"icon"`
	Header      string       `json:"header,optional"`
	KeepAlive   bool         `json:"keepAlive"`
	DefaultMenu bool         `json:"defaultMenu"`
	CloseTab    bool         `json:"closeTab"`
	Hidden      bool         `json:"hidden"`
	Code        string       `json:"code,optional"`
	Sort        int          `json:"sort"`
	Button      []SysMenuBtn `json:"btns,optional"`
}

type AnnouncementInfo struct {
	ID          uint   `json:"ID"`
	CreatedAt   string `json:"CreatedAt"`
	UpdatedAt   string `json:"UpdatedAt"`
	Title       string `json:"title"`
	Content     string `json:"content"`
	UserID      *int   `json:"userID"`
	Attachments string `json:"attachments"`
}

type AnnouncementInfoRes struct {
	Info AnnouncementInfo `json:"info"`
}

type ApiGroups struct {
	Groups []string `json:"groups"`
}

type ApisByAuthorityId struct {
	Apis []SysApi `json:"apis"`
}

type AuthorityBtnRes struct {
	Selected []uint `json:"selected"`
}

type BreakpointContinueFinishReq struct {
	FileMd5  string `json:"fileMd5"`
	SliceNum int    `json:"sliceNum"`
	File     string `json:"file"`
	FileName string `json:"fileName"`
}

type BreakpointContinueReq struct {
	File      string `json:"file"`
	SliceNum  int    `json:"sliceNum"`
	SliceSize int64  `json:"sliceSize"`
	FileSize  int64  `json:"fileSize"`
	Md5       string `json:"md5"`
	FileName  string `json:"fileName"`
}

type Captcha struct {
	CaptchaId     string `json:"captchaId"`
	PicPath       string `json:"picPath"`
	CaptchaLength int    `json:"captchaLength"`
	OpenCaptcha   bool   `json:"openCaptcha"`
}

type CasbinInfo struct {
	Path   string   `json:"path"`
	Method string   `json:"method"`
	Roles  []string `json:"roles"`
}

type CasbinRes struct {
	List []CasbinInfo `json:"list"`
}

type ChangePasswordReq struct {
	Password    string `json:"password"`
	NewPassword string `json:"newPassword"`
}

type ChangeUserInfoReq struct {
	ID           uint   `json:"id"`
	NickName     string `json:"nickName,optional"`
	Phone        string `json:"phone,optional"`
	AuthorityIds []uint `json:"authorityIds,optional"`
	Email        string `json:"email,optional"`
	HeaderImg    string `json:"headerImg,optional"`
	Enable       int    `json:"enable,optional"`
}

type ColumnInfo struct {
	ID             uint   `json:"ID"`
	CreatedAt      string `json:"CreatedAt"`
	UpdatedAt      string `json:"UpdatedAt"`
	TableId        uint   `json:"tableId"`
	ColumnName     string `json:"columnName"`
	DataType       string `json:"dataType"`
	DataTypeLong   string `json:"dataTypeLong"`
	ColumnComment  string `json:"columnComment"`
	ColumnType     string `json:"columnType"`
	FieldName      string `json:"field_name"`
	FieldJson      string `json:"field_json"`
	Required       bool   `json:"required"`
	FieldSearchTag string `json:"field_search_tag"`
	Error          string `json:"error"`
}

type CopyAuthorityReq struct {
	SysAuthority
	OldAuthorityId uint `json:"oldAuthorityId"`
}

type CreateAnnouncementInfoReq struct {
	Title       string `json:"title"`
	Content     string `json:"content"`
	UserID      *int   `json:"userID,optional"`
	Attachments string `json:"attachments,optional"`
}

type CreateApiReq struct {
	Method      string `json:"method"`
	Path        string `json:"path"`
	ApiGroup    string `json:"apiGroup"`
	Description string `json:"description"`
}

type CreateApiTokenReq struct {
	Name string `json:"name"`
}

type CreateApiTokenRes struct {
	Token SysApiToken `json:"token"`
}

type CreateAuthorityBtnReq struct {
	Name  string `json:"name"`
	Desc  string `json:"desc"`
	BtnId uint   `json:"btnId"`
}

type CreateAuthorityReq struct {
	AuthorityId   uint   `json:"authorityId"`
	AuthorityName string `json:"authorityName"`
	ParentId      uint   `json:"parentId"`
	DefaultRouter string `json:"defaultRouter"`
	DataScope     string `json:"dataScope"`
}

type CreateExaCustomerReq struct {
	CustomerName      string `json:"customerName"`
	CustomerPhoneData string `json:"customerPhoneData"`
}

type CreateHistoryReq struct {
	ID       uint `json:"id"`
	Migrate  bool `json:"migrate"`
	Rollback bool `json:"rollback"`
}

type CreatePackageReq struct {
	PackageName string `json:"packageName"`
}

type CreateReferenceReq struct {
	Name    string `json:"name"`
	Content string `json:"content"`
}

type CreateResourceReq struct {
	Name    string `json:"name"`
	Type    string `json:"type"`
	Content string `json:"content"`
}

type CreateScriptReq struct {
	Name    string `json:"name"`
	Content string `json:"content"`
}

type CreateSysDictionaryDetailReq struct {
	Label           string `json:"label,optional"`
	Value           string `json:"value,optional"`
	Extend          string `json:"extend,optional"`
	Status          *bool  `json:"status,optional"`
	Sort            int    `json:"sort,optional"`
	SysDictionaryID int    `json:"sysDictionaryID,optional"`
	ParentID        *uint  `json:"parentID,optional"`
}

type CreateSysDictionaryReq struct {
	Name     string `json:"name,optional"`
	Type     string `json:"type,optional"`
	Status   *bool  `json:"status,optional"`
	Desc     string `json:"desc,optional"`
	ParentID *uint  `json:"parentID,optional"`
}

type CreateSysErrorReq struct {
	Form     *string `json:"form"`
	Info     *string `json:"info"`
	Level    string  `json:"level"`
	Solution *string `json:"solution"`
	Status   string  `json:"status"`
}

type CreateSysParamsReq struct {
	Name  string `json:"name"`
	Key   string `json:"key"`
	Value string `json:"value"`
	Desc  string `json:"desc"`
}

type CreateTemplateReq struct {
	Name        string `json:"name,optional"`
	TableName   string `json:"tableName,optional"`
	DataType    string `json:"dataType,optional"`
	DbName      string `json:"dbName,optional"`
	PackageName string `json:"packageName,optional"`
	ModuleName  string `json:"moduleName,optional"`
}

type DBInfo struct {
	ID        uint   `json:"id"`
	Name      string `json:"name"`
	CreatedAt int64  `json:"createdAt"`
}

type DeleteAIWorkflowSessionReq struct {
	ID uint `json:"id"`
}

type DeleteAnnouncementInfoByIdsReq struct {
	IDs []uint `json:"IDs"`
}

type DeleteAnnouncementInfoReq struct {
	ID uint `json:"ID"`
}

type DeleteApiTokenReq struct {
	ID uint `json:"id"`
}

type DeleteHistoryReq struct {
	ID uint `json:"id"`
}

type DeleteLoginLogByIdsReq struct {
	Ids []uint `json:"ids"`
}

type DeleteLoginLogReq struct {
	ID uint `json:"id"`
}

type DeleteMenuReq struct {
	ID uint `json:"id"`
}

type DeletePackageReq struct {
	ID uint `json:"id"`
}

type DeleteSkillReq struct {
	ID uint `json:"id"`
}

type DeleteSysDictionaryDetailReq struct {
	ID uint `json:"ID,optional"`
}

type DeleteSysDictionaryReq struct {
	ID uint `json:"ID,optional"`
}

type DeleteSysErrorByIdsReq struct {
	Ids []uint `json:"ids"`
}

type DeleteSysErrorReq struct {
	ID uint `json:"id"`
}

type DeleteSysOperationRecordByIdsReq struct {
	Ids []uint `json:"ids"`
}

type DeleteSysOperationRecordReq struct {
	ID uint `json:"id"`
}

type DeleteSysVersionReq struct {
	ID uint `json:"id"`
}

type DictionaryPath struct {
	ID   uint   `json:"id"`
	Name string `json:"name"`
}

type DictionaryPathRes struct {
	Path []SysDictionaryDetail `json:"path"`
}

type DictionaryTree struct {
	ID       uint             `json:"id"`
	Name     string           `json:"name"`
	Type     string           `json:"type"`
	Children []DictionaryTree `json:"children"`
}

type DictionaryTreeRes struct {
	List []SysDictionaryDetail `json:"list"`
}

type Disk struct {
	Path   string  `json:"path"`
	Total  uint64  `json:"total"`
	Free   uint64  `json:"free"`
	Used   uint64  `json:"used"`
	Inodes uint64  `json:"inodes"`
	Perc   float64 `json:"perc"`
}

type DownloadOnlineSkillReq struct {
	Url string `json:"url"`
}

type DownloadOnlineSkillRes struct {
	Success bool `json:"success"`
}

type DumpAIWorkflowMarkdownReq struct {
	ID uint `json:"id"`
}

type EditFileNameReq struct {
	ID   uint   `json:"id"`
	Name string `json:"name"`
}

type EmailSendReq struct {
	To      string `json:"to"`
	Subject string `json:"subject"`
	Body    string `json:"body"`
}

type ExaAttachmentCategory struct {
	ID        uint                    `json:"ID"`
	CreatedAt string                  `json:"CreatedAt"`
	UpdatedAt string                  `json:"UpdatedAt"`
	Name      string                  `json:"name"`
	Pid       uint                    `json:"pid"`
	Children  []ExaAttachmentCategory `json:"children"`
}

type ExaAttachmentCategoryRes struct {
	Category ExaAttachmentCategory `json:"category"`
}

type ExaCustomer struct {
	ID                 uint    `json:"ID"`
	CreatedAt          string  `json:"CreatedAt"`
	UpdatedAt          string  `json:"UpdatedAt"`
	CustomerName       string  `json:"customerName"`
	CustomerPhoneData  string  `json:"customerPhoneData"`
	SysUserID          uint    `json:"sysUserId"`
	SysUserAuthorityID uint    `json:"sysUserAuthorityID"`
	SysUser            SysUser `json:"sysUser"`
}

type ExaCustomerRes struct {
	Customer ExaCustomer `json:"customer"`
}

type ExaFileRes struct {
	File ExaFileUploadAndDownload `json:"file"`
}

type ExaFileUploadAndDownload struct {
	ID        uint   `json:"ID"`
	CreatedAt string `json:"CreatedAt"`
	UpdatedAt string `json:"UpdatedAt"`
	Name      string `json:"name"`
	ClassId   int    `json:"classId"`
	Url       string `json:"url"`
	Tag       string `json:"tag"`
	Key       string `json:"key"`
	Size      int64  `json:"size"`
}

type ExportSysDictionaryDetail struct {
	Label  string `json:"label"`
	Value  string `json:"value"`
	Extend string `json:"extend"`
	Status *bool  `json:"status"`
	Sort   int    `json:"sort"`
	Level  int    `json:"level"`
	Path   string `json:"path"`
}

type ExportSysDictionaryRes struct {
	Name                 string                      `json:"name"`
	Type                 string                      `json:"type"`
	Status               *bool                       `json:"status"`
	Desc                 string                      `json:"desc"`
	SysDictionaryDetails []ExportSysDictionaryDetail `json:"sysDictionaryDetails"`
}

type ExportTemplateReq struct {
	TemplateID string `json:"templateID,optional" form:"templateID,optional"`
}

type ExportVersionReq struct {
	ID uint `json:"id"`
}

type FindAnnouncementInfoReq struct {
	ID *uint `json:"ID,optional" form:"ID,optional"`
}

type FindSysDictionaryReq struct {
	ID     uint   `json:"ID,optional" form:"ID,optional"`
	Type   string `json:"type,optional" form:"type,optional"`
	Status *bool  `json:"status,optional" form:"status,optional"`
}

type GetAIWorkflowSessionListReq struct {
	PageInfo
}

type GetAllApisReq struct {
	Method      string `json:"method,optional"`
	Path        string `json:"path,optional"`
	Description string `json:"description,optional"`
}

type GetAnnouncementInfoListReq struct {
	PageInfo
	StartCreatedAt string `json:"startCreatedAt,optional" form:"startCreatedAt,optional"`
	EndCreatedAt   string `json:"endCreatedAt,optional" form:"endCreatedAt,optional"`
}

type GetApiListReq struct {
	PageInfo
	Method      string `json:"method,optional"`
	Path        string `json:"path,optional"`
	Description string `json:"description,optional"`
	ApiGroup    string `json:"apiGroup,optional"`
	OrderKey    string `json:"orderKey,optional"`
	Desc        bool   `json:"desc,optional"`
}

type GetApiRolesReq struct {
	Path   string `json:"path,optional" form:"path,optional"`
	Method string `json:"method,optional" form:"method,optional"`
}

type GetApiTokenListReq struct {
	PageInfo
}

type GetAuthorityBtnReq struct {
	AuthorityId uint `json:"authorityId"`
	MenuId      uint `json:"menuId"`
}

type GetAuthorityListReq struct {
	PageInfo
}

type GetById struct {
	ID int `json:"id,optional" form:"ID,optional"`
}

type GetByLowerId struct {
	ID int `json:"id,optional" form:"id,optional"`
}

type GetDictionaryDetailsByParentReq struct {
	SysDictionaryID int   `json:"sysDictionaryID,optional" form:"sysDictionaryID,optional"`
	ParentID        *uint `json:"parentID,optional" form:"parentID,optional"`
	IncludeChildren bool  `json:"includeChildren,optional" form:"includeChildren,optional"`
}

type GetDictionaryTreeListByTypeReq struct {
	Type string `json:"type,optional" form:"type,optional"`
}

type GetDictionaryTreeListReq struct {
	SysDictionaryID int `json:"sysDictionaryID,optional" form:"sysDictionaryID,optional"`
}

type GetExaCustomerListReq struct {
	PageInfo
}

type GetExaFileListReq struct {
	PageInfo
}

type GetHistoryListReq struct {
	PageInfo
}

type GetInfoPublicRes struct {
	Success bool               `json:"success"`
	Data    InfoDataSourceItem `json:"data"`
}

type GetLoginLogListReq struct {
	PageInfo
	Username string `json:"username,optional" form:"Username,optional"`
	Ip       string `json:"ip,optional" form:"Ip,optional"`
	Status   bool   `json:"status,optional" form:"Status,optional"`
}

type GetPolicyPathByAuthorityIdReq struct {
	AuthorityId string `json:"authorityId"`
}

type GetReferenceReq struct {
	ID uint `json:"id"`
}

type GetResourceReq struct {
	ID uint `json:"id"`
}

type GetScriptReq struct {
	ID uint `json:"id"`
}

type GetSkillListReq struct {
	PageInfo
}

type GetSysDictionaryDetailListReq struct {
	PageInfo
	Label           string `json:"label,optional" form:"label,optional"`
	Value           string `json:"value,optional" form:"value,optional"`
	SysDictionaryID uint   `json:"sysDictionaryID,optional" form:"sysDictionaryID,optional"`
}

type GetSysDictionaryListReq struct {
	PageInfo
	Name string `json:"name,optional" form:"name,optional"`
}

type GetSysErrorListReq struct {
	PageInfo
}

type GetSysOperationRecordListReq struct {
	PageInfo
	UserId uint   `json:"user_id,optional" form:"user_id,optional"`
	Method string `json:"method,optional" form:"method,optional"`
	Path   string `json:"path,optional" form:"path,optional"`
	Ip     string `json:"ip,optional" form:"ip,optional"`
	Agent  string `json:"agent,optional" form:"agent,optional"`
}

type GetSysVersionListReq struct {
	PageInfo
}

type GetTemplateReq struct {
	ID uint `json:"id"`
}

type GetUserListReq struct {
	PageInfo
	Username string `json:"username,optional" form:"username,optional"`
	NickName string `json:"nickName,optional" form:"nickName,optional"`
	Phone    string `json:"phone,optional" form:"phone,optional"`
	Email    string `json:"email,optional" form:"email,optional"`
	OrderKey string `json:"orderKey,optional" form:"orderKey,optional"`
	Desc     bool   `json:"desc,optional" form:"desc,optional"`
}

type GlobalConstraint struct {
	ID        uint   `json:"ID"`
	CreatedAt string `json:"CreatedAt"`
	UpdatedAt string `json:"UpdatedAt"`
	Content   string `json:"content"`
}

type GlobalConstraintRes struct {
	Constraint GlobalConstraint `json:"constraint"`
}

type Host struct {
	Name         string  `json:"name"`
	Core         int     `json:"core"`
	Model        string  `json:"model"`
	Mhz          float64 `json:"mhz"`
	MaxLoadLimit float64 `json:"maxLoadLimit"`
	IdleLoadPerc float64 `json:"idleLoadPerc"`
	UserLoadPerc float64 `json:"userLoadPerc"`
	WcpLoadPerc  float64 `json:"wcpLoadPerc"`
	IOWait       float64 `json:"ioWait"`
}

type IdsReq struct {
	Ids []int `json:"ids"`
}

type ImportFileUrlReq struct {
	Url string `json:"url"`
}

type ImportSysDictionaryData struct {
	Name                 string                `json:"name"`
	Type                 string                `json:"type"`
	Status               *bool                 `json:"status"`
	Desc                 string                `json:"desc"`
	SysDictionaryDetails []SysDictionaryDetail `json:"sysDictionaryDetails"`
}

type ImportSysDictionaryReq struct {
	Json string `json:"json"`
}

type ImportVersionReq struct {
	Version string `json:"version"`
	Content string `json:"content"`
}

type InfoDataSourceItem struct {
	Label string `json:"label"`
	Value uint   `json:"value"`
}

type LoginReq struct {
	Username  string `json:"username"`
	Password  string `json:"password"`
	Captcha   string `json:"captcha,optional"`
	CaptchaId string `json:"captchaId,optional"`
}

type LoginResp struct {
	User      SysUser `json:"user"`
	Token     string  `json:"token"`
	ExpiresAt int64   `json:"expiresAt"`
}

type McpReq struct {
}

type McpStatusRes struct {
	Status string `json:"status"`
}

type Mem struct {
	Total uint64  `json:"total"`
	Used  uint64  `json:"used"`
	Free  uint64  `json:"free"`
	Perc  float64 `json:"perc"`
}

type MenuRes struct {
	AuthorityId uint      `json:"authorityId"`
	Menus       []SysMenu `json:"menus"`
}

type MenuRolesRes struct {
	AuthorityIds              []uint `json:"authorityIds"`
	DefaultRouterAuthorityIds []uint `json:"defaultRouterAuthorityIds"`
}

type MenuTreeRes struct {
	MenuTree []SysMenu `json:"menus"`
}

type Meta struct {
	Title          string `json:"title"`
	Icon           string `json:"icon"`
	KeepAlive      bool   `json:"keepAlive"`
	DefaultMenu    bool   `json:"defaultMenu"`
	CloseTab       bool   `json:"closeTab"`
	TransitionType string `json:"transitionType"`
}

type Os struct {
	Arch     string `json:"arch"`
	Hostname string `json:"hostname"`
	Kernel   string `json:"kernel"`
	System   string `json:"system"`
	Platform string `json:"platform"`
	Uptime   uint64 `json:"uptime"`
	HostID   string `json:"hostID"`
}

type PackageInfo struct {
	ID          uint   `json:"ID"`
	CreatedAt   string `json:"CreatedAt"`
	UpdatedAt   string `json:"UpdatedAt"`
	PackageName string `json:"packageName"`
	WebPath     string `json:"webPath"`
	GoModFile   string `json:"goModFile"`
}

type PackageSkillReq struct {
	ID uint `json:"id"`
}

type PageInfo struct {
	Page     int    `json:"page,optional" form:"page,optional"`
	PageSize int    `json:"pageSize,optional" form:"pageSize,optional"`
	Keyword  string `json:"keyword,optional" form:"keyword,optional"`
}

type PageResult struct {
	List     interface{} `json:"list"`
	Total    int64       `json:"total"`
	Page     int         `json:"page"`
	PageSize int         `json:"pageSize"`
}

type PreviewReq struct {
	TableName string `json:"tableName"`
}

type ReferenceDetailRes struct {
	Reference References `json:"reference"`
}

type References struct {
	ID        uint   `json:"ID"`
	CreatedAt string `json:"CreatedAt"`
	UpdatedAt string `json:"UpdatedAt"`
	Name      string `json:"name"`
	Content   string `json:"content"`
}

type ReferencesRes struct {
	References []References `json:"references"`
}

type RegisterReq struct {
	Username     string `json:"userName"`
	Password     string `json:"passWord"`
	NickName     string `json:"nickName"`
	HeaderImg    string `json:"headerImg,optional"`
	AuthorityId  uint   `json:"authorityId"`
	Enable       int    `json:"enable"`
	AuthorityIds []uint `json:"authorityIds,optional"`
	Phone        string `json:"phone,optional"`
	Email        string `json:"email,optional"`
}

type RemoveChunkReq struct {
	FileMd5 string `json:"fileMd5"`
}

type ResetPasswordReq struct {
	ID       uint   `json:"ID"`
	Password string `json:"password"`
}

type ResourceDetailRes struct {
	Resource Resources `json:"resource"`
}

type Resources struct {
	ID        uint   `json:"ID"`
	CreatedAt string `json:"CreatedAt"`
	UpdatedAt string `json:"UpdatedAt"`
	Name      string `json:"name"`
	Type      string `json:"type"`
	Content   string `json:"content"`
}

type ResourcesRes struct {
	Resources []Resources `json:"resources"`
}

type Response struct {
	Code int         `json:"code"`
	Data interface{} `json:"data"`
	Msg  string      `json:"msg"`
}

type RollBackReq struct {
	ID uint `json:"id"`
}

type SaveAIWorkflowSessionReq struct {
	Name    string `json:"name"`
	Content string `json:"content"`
}

type SaveGlobalConstraintReq struct {
	Content string `json:"content"`
}

type SaveReferenceReq struct {
	ID      uint   `json:"id,optional"`
	Name    string `json:"name"`
	Content string `json:"content"`
}

type SaveResourceReq struct {
	ID      uint   `json:"id,optional"`
	Name    string `json:"name"`
	Type    string `json:"type"`
	Content string `json:"content"`
}

type SaveScriptReq struct {
	ID      uint   `json:"id,optional"`
	Name    string `json:"name"`
	Content string `json:"content"`
}

type SaveSkillReq struct {
	ID      uint   `json:"id,optional"`
	Name    string `json:"name"`
	Desc    string `json:"desc"`
	Content string `json:"content"`
}

type SaveTemplateReq struct {
	ID      uint   `json:"id,optional"`
	Name    string `json:"name"`
	Content string `json:"content"`
}

type ScriptDetailRes struct {
	Script Scripts `json:"script"`
}

type Scripts struct {
	ID        uint   `json:"ID"`
	CreatedAt string `json:"CreatedAt"`
	UpdatedAt string `json:"UpdatedAt"`
	Name      string `json:"name"`
	Content   string `json:"content"`
}

type ScriptsRes struct {
	Scripts []Scripts `json:"scripts"`
}

type ServerInfo struct {
	Cpu  []string `json:"cpu"`
	Host Host     `json:"host"`
	Mem  Mem      `json:"mem"`
	Os   Os       `json:"os"`
	Disk []Disk   `json:"disk"`
}

type SetApiRolesReq struct {
	Path         string `json:"path"`
	Method       string `json:"method"`
	AuthorityIds []uint `json:"authorityIds"`
}

type SetAuthorityBtnReq struct {
	MenuId      uint   `json:"menuId"`
	AuthorityId uint   `json:"authorityId"`
	Selected    []uint `json:"selected"`
}

type SetDataAuthorityReq struct {
	DataScope   string `json:"dataScope"`
	AuthorityId uint   `json:"authorityId"`
}

type SetMenuRolesReq struct {
	MenuId       uint   `json:"menuId,optional" form:"menuId,optional"`
	AuthorityIds []uint `json:"authorityIds,optional" form:"authorityIds,optional"`
}

type SetRoleUsersReq struct {
	AuthorityId uint   `json:"authorityId,optional" form:"authorityId,optional"`
	UserIds     []uint `json:"userIds,optional" form:"userIds,optional"`
}

type SetUserAuthReq struct {
	AuthorityId uint `json:"authorityId"`
}

type SetUserAuthoritiesReq struct {
	ID           uint   `json:"ID"`
	AuthorityIds []uint `json:"authorityIds"`
}

type SkillDetailRes struct {
	Skill Skills `json:"skill"`
}

type Skills struct {
	ID        uint   `json:"ID"`
	CreatedAt string `json:"CreatedAt"`
	UpdatedAt string `json:"UpdatedAt"`
	Name      string `json:"name"`
	Desc      string `json:"desc"`
	Content   string `json:"content"`
}

type SkillsRes struct {
	Skills []Skills `json:"skills"`
}

type SqlPreviewRes struct {
	Sql string `json:"sql"`
}

type SyncApiItem struct {
	Path   string `json:"path"`
	Method string `json:"method"`
}

type SyncApiReq struct {
	NewApis    []SyncApiItem `json:"newApis,optional"`
	DeleteApis []SyncApiItem `json:"deleteApis,optional"`
	IgnoreApis []SyncApiItem `json:"ignoreApis,optional"`
}

type SyncApiResp struct {
	NewApis    []SysApi `json:"newApis"`
	DeleteApis []SysApi `json:"deleteApis"`
	IgnoreApis []SysApi `json:"ignoreApis"`
}

type SysApi struct {
	ID          uint   `json:"ID"`
	CreatedAt   string `json:"CreatedAt"`
	UpdatedAt   string `json:"UpdatedAt"`
	Method      string `json:"method"`
	Path        string `json:"path"`
	ApiGroup    string `json:"apiGroup"`
	Description string `json:"description"`
}

type SysApiToken struct {
	ID          uint   `json:"ID"`
	CreatedAt   string `json:"CreatedAt"`
	UpdatedAt   string `json:"UpdatedAt"`
	UserID      uint   `json:"userId"`
	AuthorityID uint   `json:"authorityId"`
	Token       string `json:"token"`
	Name        string `json:"name"`
	Status      bool   `json:"status"`
	ExpiresAt   string `json:"expiresAt"`
	Remark      string `json:"remark"`
}

type SysAuthority struct {
	CreatedAt      string         `json:"CreatedAt"`
	UpdatedAt      string         `json:"UpdatedAt"`
	AuthorityId    uint           `json:"authorityId"`
	AuthorityName  string         `json:"authorityName"`
	ParentId       uint           `json:"parentId"`
	DefaultRouter  string         `json:"defaultRouter"`
	DataScope      string         `json:"dataScope"`
	Children       []SysAuthority `json:"children"`
	Menus          []SysMenu      `json:"menus"`
	Local          *bool          `json:"local"`
	AuthorityIdStr string         `json:"authorityIdStr"`
}

type SysAuthorityBtn struct {
	ID        uint   `json:"ID"`
	CreatedAt string `json:"CreatedAt"`
	UpdatedAt string `json:"UpdatedAt"`
	Name      string `json:"name"`
	Desc      string `json:"desc"`
	BtnId     uint   `json:"btnId"`
}

type SysAutoCodeHistory struct {
	ID        uint   `json:"ID"`
	CreatedAt string `json:"CreatedAt"`
	UpdatedAt string `json:"UpdatedAt"`
	TableName string `json:"tableName"`
	Voice     string `json:"voice"`
	Template  string `json:"template"`
	Author    string `json:"author"`
	Migrate   bool   `json:"migrate"`
	Rollback  bool   `json:"rollback"`
}

type SysDictionary struct {
	ID        uint            `json:"ID"`
	CreatedAt string          `json:"CreatedAt"`
	UpdatedAt string          `json:"UpdatedAt"`
	Name      string          `json:"name"`
	Type      string          `json:"type"`
	Status    *bool           `json:"status"`
	Desc      string          `json:"desc"`
	ParentID  *uint           `json:"parentID"`
	Children  []SysDictionary `json:"children"`
}

type SysDictionaryDetail struct {
	ID              uint                  `json:"ID"`
	CreatedAt       string                `json:"CreatedAt"`
	UpdatedAt       string                `json:"UpdatedAt"`
	Label           string                `json:"label"`
	Value           string                `json:"value"`
	Extend          string                `json:"extend"`
	Status          *bool                 `json:"status"`
	Sort            int                   `json:"sort"`
	SysDictionaryID int                   `json:"sysDictionaryID"`
	ParentID        *uint                 `json:"parentID"`
	Children        []SysDictionaryDetail `json:"children"`
	Level           int                   `json:"level"`
	Path            string                `json:"path"`
	Disabled        bool                  `json:"disabled"`
}

type SysDictionaryDetailRes struct {
	ReSysDictionaryDetail SysDictionaryDetail `json:"reSysDictionaryDetail"`
}

type SysDictionaryRes struct {
	ResysDictionary SysDictionary `json:"resysDictionary"`
}

type SysError struct {
	ID        uint    `json:"ID"`
	CreatedAt string  `json:"CreatedAt"`
	UpdatedAt string  `json:"UpdatedAt"`
	Form      *string `json:"form"`
	Info      *string `json:"info"`
	Level     string  `json:"level"`
	Solution  *string `json:"solution"`
	Status    string  `json:"status"`
}

type SysErrorRes struct {
	ErrorInfo SysError `json:"error"`
}

type SysLoginLog struct {
	ID           uint   `json:"ID"`
	CreatedAt    string `json:"CreatedAt"`
	UpdatedAt    string `json:"UpdatedAt"`
	Username     string `json:"username"`
	Ip           string `json:"ip"`
	Agent        string `json:"agent"`
	Status       bool   `json:"status"`
	ErrorMessage string `json:"errorMessage"`
	UserId       uint   `json:"userId"`
}

type SysLoginLogRes struct {
	LoginLog SysLoginLog `json:"loginLog"`
}

type SysMenu struct {
	ID          uint               `json:"ID"`
	CreatedAt   string             `json:"CreatedAt"`
	UpdatedAt   string             `json:"UpdatedAt"`
	MenuLevel   uint               `json:"menuLevel"`
	ParentId    uint               `json:"parentId"`
	Path        string             `json:"path"`
	Name        string             `json:"name"`
	Hidden      bool               `json:"hidden"`
	Component   string             `json:"component"`
	Sort        int                `json:"sort"`
	Meta        Meta               `json:"meta"`
	AuthorityId uint               `json:"authorityId"`
	Button      []SysMenuBtn       `json:"menuBtn"`
	Buttons     []SysAuthorityBtn  `json:"buttons"`
	HideTab     bool               `json:"hideTab"`
	MenuId      uint               `json:"menuId"`
	Children    []SysMenu          `json:"children"`
	Parameters  []SysMenuParameter `json:"parameters"`
}

type SysMenuBtn struct {
	ID        uint   `json:"ID"`
	CreatedAt string `json:"CreatedAt"`
	UpdatedAt string `json:"UpdatedAt"`
	Name      string `json:"name"`
	Desc      string `json:"desc"`
	ButtonId  uint   `json:"buttonId"`
}

type SysMenuParameter struct {
	ID            uint   `json:"ID"`
	SysBaseMenuID uint   `json:"sysBaseMenuID"`
	Type          string `json:"type"`
	Key           string `json:"key"`
	Value         string `json:"value"`
}

type SysOperationRecord struct {
	ID        uint   `json:"ID"`
	CreatedAt string `json:"CreatedAt"`
	UpdatedAt string `json:"UpdatedAt"`
	UserId    uint   `json:"user_id"`
	Ip        string `json:"ip"`
	Method    string `json:"method"`
	Path      string `json:"path"`
	Agent     string `json:"agent"`
	Status    int    `json:"status"`
	Latency   int64  `json:"latency"`
	Body      string `json:"body"`
	Resp      string `json:"resp"`
}

type SysOperationRecordRes struct {
	SysOperationRecord SysOperationRecord `json:"sysOperationRecord"`
}

type SysUser struct {
	ID            uint           `json:"ID"`
	CreatedAt     string         `json:"CreatedAt"`
	UpdatedAt     string         `json:"UpdatedAt"`
	UUID          string         `json:"uuid"`
	Username      string         `json:"userName"`
	NickName      string         `json:"nickName"`
	Password      string         `json:"-"`
	HeaderImg     string         `json:"headerImg"`
	AuthorityId   uint           `json:"authorityId"`
	Authority     SysAuthority   `json:"authority"`
	Authorities   []SysAuthority `json:"authorities"`
	Phone         string         `json:"phone"`
	Email         string         `json:"email"`
	Enable        int            `json:"enable"`
	OriginSetting interface{}    `json:"originSetting"`
}

type SysUserResponse struct {
	User SysUser `json:"user"`
}

type SysVersion struct {
	ID          uint    `json:"ID"`
	CreatedAt   string  `json:"CreatedAt"`
	UpdatedAt   string  `json:"UpdatedAt"`
	VersionName *string `json:"versionName"`
	VersionCode *string `json:"versionCode"`
	Description *string `json:"description"`
	VersionData *string `json:"versionData"`
}

type SysVersionRes struct {
	Version SysVersion `json:"version"`
}

type System struct {
	RouterPrefix  string `json:"routerPrefix"`
	UseMultipoint bool   `json:"useMultipoint"`
	ConfigPath    string `json:"configPath"`
}

type SystemConfig struct {
	System System `json:"system"`
}

type TableInfo struct {
	ID            uint   `json:"ID"`
	CreatedAt     string `json:"CreatedAt"`
	UpdatedAt     string `json:"UpdatedAt"`
	TableName     string `json:"tableName"`
	TableComment  string `json:"tableComment"`
	Class         string `json:"class"`
	Package       string `json:"package"`
	ProductModule string `json:"productModule"`
}

type TemplateDetailRes struct {
	Template Templates `json:"template"`
}

type Templates struct {
	ID        uint   `json:"ID"`
	CreatedAt string `json:"CreatedAt"`
	UpdatedAt string `json:"UpdatedAt"`
	Name      string `json:"name"`
	Content   string `json:"content"`
}

type TemplatesRes struct {
	Templates []Templates `json:"templates"`
}

type UpdateAnnouncementInfoReq struct {
	ID          uint   `json:"ID"`
	Title       string `json:"title"`
	Content     string `json:"content"`
	UserID      *int   `json:"userID,optional"`
	Attachments string `json:"attachments,optional"`
}

type UpdateApiReq struct {
	ID          uint   `json:"id"`
	Method      string `json:"method"`
	Path        string `json:"path"`
	ApiGroup    string `json:"apiGroup"`
	Description string `json:"description"`
}

type UpdateAuthorityReq struct {
	ID            uint   `json:"id"`
	AuthorityId   uint   `json:"authorityId"`
	AuthorityName string `json:"authorityName"`
	ParentId      uint   `json:"parentId"`
	DefaultRouter string `json:"defaultRouter"`
	DataScope     string `json:"dataScope"`
}

type UpdateCasbinReq struct {
	AuthorityId uint         `json:"authorityId"`
	CasbinInfos []CasbinInfo `json:"casbinInfos"`
}

type UpdateExaCustomerReq struct {
	ID                uint   `json:"id"`
	CustomerName      string `json:"customerName"`
	CustomerPhoneData string `json:"customerPhoneData"`
}

type UpdateMenuReq struct {
	ID          uint         `json:"id"`
	CreatedAt   int64        `json:"createdAt,optional"`
	UpdatedAt   int64        `json:"updatedAt,optional"`
	DeletedAt   int64        `json:"deletedAt,optional"`
	MenuLevel   uint         `json:"menuLevel"`
	ParentId    uint         `json:"parentId"`
	Path        string       `json:"path"`
	Name        string       `json:"name"`
	Component   string       `json:"component"`
	Redirect    string       `json:"redirect,optional"`
	Title       string       `json:"title"`
	Icon        string       `json:"icon"`
	Header      string       `json:"header,optional"`
	KeepAlive   bool         `json:"keepAlive"`
	DefaultMenu bool         `json:"defaultMenu"`
	CloseTab    bool         `json:"closeTab"`
	Hidden      bool         `json:"hidden"`
	Code        string       `json:"code,optional"`
	Sort        int          `json:"sort"`
	Button      []SysMenuBtn `json:"btns,optional"`
}

type UpdateSysDictionaryDetailReq struct {
	ID              uint   `json:"ID,optional"`
	Label           string `json:"label,optional"`
	Value           string `json:"value,optional"`
	Extend          string `json:"extend,optional"`
	Status          *bool  `json:"status,optional"`
	Sort            int    `json:"sort,optional"`
	SysDictionaryID int    `json:"sysDictionaryID,optional"`
	ParentID        *uint  `json:"parentID,optional"`
}

type UpdateSysDictionaryReq struct {
	ID       uint   `json:"ID,optional"`
	Name     string `json:"name,optional"`
	Type     string `json:"type,optional"`
	Status   *bool  `json:"status,optional"`
	Desc     string `json:"desc,optional"`
	ParentID *uint  `json:"parentID,optional"`
}

type UpdateSysErrorReq struct {
	ID       uint    `json:"id"`
	Form     *string `json:"form"`
	Info     *string `json:"info"`
	Level    string  `json:"level"`
	Solution *string `json:"solution"`
	Status   string  `json:"status"`
}

type UpdateSysParamsReq struct {
	ID    uint   `json:"id"`
	Name  string `json:"name"`
	Key   string `json:"key"`
	Value string `json:"value"`
	Desc  string `json:"desc"`
}

type UserInfoRes struct {
	UserInfo SysUser `json:"userInfo"`
}

type UsersByAuthorityId struct {
	Users []SysUser `json:"users"`
}
